<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [ ]:
!pip install pandas
!pip install matplotlib

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [1]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [2]:
# Write your code here
l_dtypes = list(df.dtypes)
l_dtypes
l_counts = df.count()
l_counts
l_msvals = df.isnull().sum()
l_msvals
df_info = pd.DataFrame({'DTypes':l_dtypes,'Counts':l_counts,'Missing values':l_msvals}, index=df.columns)
df_info

                      DTypes  Counts  Missing values
ResponseId             int64   65437               0
MainBranch            object   65437               0
Age                   object   65437               0
Employment            object   65437               0
RemoteWork            object   54806           10631
...                      ...     ...             ...
JobSatPoints_11      float64   29445           35992
SurveyLength          object   56182            9255
SurveyEase            object   56238            9199
ConvertedCompYearly  float64   23435           42002
JobSat               float64   29126           36311

[114 rows x 3 columns]

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [3]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [4]:
country_list = df['Country'].value_counts().sort_index()
cl = ''
for c in country_list.index:
    cl += c
    cl += '\n'
with open("countries.txt","w") as f:
    f.write(cl)

In [5]:
# Write your code here
irrelevant_list = ['Nomadic']
df.loc[df['Country'].isin(irrelevant_list),'Country'].count()

np.int64(43)

In [6]:
rename_map = {
    "Democratic People's Republic of Korea": "North Korea",
    "Republic of Korea": "South Korea",
    "Viet Nam": "Vietnam",
    "Swaziland": "Eswatini",
    "Libyan Arab Jamahiriya": "Libya",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "United States of America": "United States",
    "Congo, Republic of the...": "Republic of the Congo",
    "Iran, Islamic Republic of...": "Iran",
    "Micronesia, Federated States of...": "Micronesia",
    "Venezuela, Bolivarian Republic of...": "Venezuela"
}

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [7]:
## Write your code here
# Write your code here
irrelevant_list = ['Nomadic']
df.loc[df['Country'].isin(irrelevant_list),'Country'] = None

rename_map = {
    "Democratic People's Republic of Korea": "North Korea",
    "Republic of Korea": "South Korea",
#    "Viet Nam": "Vietnam",
#    "Swaziland": "Eswatini",
#    "Libyan Arab Jamahiriya": "Libya",
#    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
#    "United States of America": "United States",
    "Congo, Republic of the...": "Republic of the Congo",
    "Iran, Islamic Republic of...": "Iran",
    "Micronesia, Federated States of...": "Micronesia",
    "Venezuela, Bolivarian Republic of...": "Venezuela"
}

df['Country'] = df['Country'].replace(rename_map)

In [8]:
print('Number of Normadic = ',df[df['Country']=='Normadic']['Country'].count())
for a in rename_map:
    f_ents = df[df['Country']==a]['Country'].count()
    s_ents = df[df['Country']==rename_map[a]]['Country'].count()
    print(f"{a:>53} : {rename_map[a]:22} {f_ents:5} :{s_ents:5}")

Number of Normadic =  0
                Democratic People's Republic of Korea : North Korea                0 :    5
                                    Republic of Korea : South Korea                0 :  203
                            Congo, Republic of the... : Republic of the Congo      0 :    8
                         Iran, Islamic Republic of... : Iran                       0 :  411
                   Micronesia, Federated States of... : Micronesia                 0 :    1
                 Venezuela, Bolivarian Republic of... : Venezuela                  0 :   69

In [9]:
#EdLevel
df['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          24942
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       15557
Some college/university study without earning a degree                                 7651
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     5793
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2970
Associate degree (A.A., A.S., etc.)                                                    1793
Primary/elementary school                                                              1146
Something else                                                                          932
Name: count, dtype: int64

### 4. Encoding Categorical Variables

In [10]:
df['Employment'].str.split(';').explode().value_counts()

Employment
Employed, full-time                                     45162
Independent contractor, freelancer, or self-employed    10726
Student, full-time                                       8626
Employed, part-time                                      4145
Not employed, but looking for work                       3954
Student, part-time                                       2656
Not employed, and not looking for work                   1203
Retired                                                   681
I prefer not to say                                       546
Name: count, dtype: int64

In [11]:
r = df["Employment"].str.extract(r"^(Employed|Independent|Not employed|Student)")[0]
r.value_counts()

0
Employed        46436
Student          8611
Independent      5574
Not employed     3745
Name: count, dtype: int64

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [12]:
## Write your code here
encoded_df = pd.get_dummies(r,prefix="Employment", dtype=int, ) 
encoded_df.head()

,Employment_Employed,Employment_Independent,Employment_Not employed,Employment_Student
0,1,0,0,0
1,1,0,0,0
2,1,0,0,0
3,0,0,0,1
4,0,0,0,1

In [13]:
df = pd.concat([df, encoded_df], axis=1)
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat', 'Employment_Employed',
       'Employment_Independent', 'Employment_Not employed',
       'Employment_Student'],
      dtype='object', length=118)

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [14]:
## Write your code here
missing_values = df.isnull().sum()
missing_values[missing_values == missing_values.max()]

AINextMuch less integrated    64289
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [15]:
## Write your code here
df.select_dtypes(include=['number'])

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat,Employment_Employed,Employment_Independent,Employment_Not employed,Employment_Student
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0
1,2,NaN,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1,0,0,0
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0
65433,65434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0
65434,65435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0
65435,65436,NaN,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1,0,0,0
65436,65437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1

In [16]:
df['ConvertedCompYearly'].isnull().sum()

np.int64(42002)

In [17]:
df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].median(), inplace=True)
df['ConvertedCompYearly'].isnull().sum()

C:\Users\IMST\AppData\Local\Temp\ipykernel_16308\2650577957.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].median(), inplace=True)

np.int64(0)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [18]:
## Write your code here
print(df['RemoteWork'].value_counts())
print(df['RemoteWork'].isnull().sum())
df['RemoteWork'].fillna(df['RemoteWork'].mode()[0], inplace=True)
print(df['RemoteWork'].value_counts())
print(df['RemoteWork'].isnull().sum())

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: count, dtype: int64
10631
RemoteWork
Hybrid (some remote, some in-person)    33646
Remote                                  20831
In-person                               10960
Name: count, dtype: int64
0

C:\Users\IMST\AppData\Local\Temp\ipykernel_16308\742126274.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RemoteWork'].fillna(df['RemoteWork'].mode()[0], inplace=True)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [19]:
## Write your code here
dfc = df['ConvertedCompYearly']
dfc.value_counts()
des = dfc.describe()
Min = dfc.min()
Max = dfc.max()
dfc_m = dfc / (Max-Min)
dfc_m.value_counts()

ConvertedCompYearly
0.003998    42039
0.003964      321
0.003303      308
0.004625      230
0.005286      226
            ...
0.000268        1
0.000962        1
0.000597        1
0.003614        1
0.000247        1
Name: count, Length: 6113, dtype: int64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [20]:
## Write your code here
dfc.describe()

count    6.543700e+04
mean     7.257636e+04
std      1.122207e+05
min      1.000000e+00
25%      6.500000e+04
50%      6.500000e+04
75%      6.500000e+04
max      1.625660e+07
Name: ConvertedCompYearly, dtype: float64

In [25]:
import numpy as np
dfc_l = np.log10(dfc)
print(dfc.value_counts())
print(dfc_l.value_counts())

ConvertedCompYearly
65000.0    42039
64444.0      321
53703.0      308
75184.0      230
85925.0      226
           ...
4364.0         1
15637.0        1
9711.0         1
58751.0        1
4019.0         1
Name: count, Length: 6113, dtype: int64
ConvertedCompYearly
4.812913    42039
4.809182      321
4.729999      308
4.876125      230
4.934120      226
            ...
3.639885        1
4.194153        1
3.987264        1
4.769015        1
3.604118        1
Name: count, Length: 6113, dtype: int64

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [30]:
## Write your code here
df['YearsCodePro'].value_counts().sort_index(key=lambda x: pd.to_numeric(x, errors='coerce'))

YearsCodePro
1                     2639
2                     4168
3                     4093
4                     3215
5                     3526
6                     2843
7                     2517
8                     2549
9                     1493
10                    3251
11                    1312
12                    1777
13                    1127
14                    1082
15                    1635
16                     946
17                     814
18                     867
19                     516
20                    1549
21                     380
22                     492
23                     448
24                     632
25                     998
26                     426
27                     380
28                     342
29                     196
30                     689
31                     106
32                     194
33                     132
34                     169
35                     285
36                     119
37                     104
38                     134
39                      54
40                     194
41                      51
42                      55
43                      37
44                      42
45                      56
46                      21
47                      10
48                      14
49                      11
50                      14
Less than 1 year      2856
More than 50 years      50
Name: count, dtype: int64

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.